### ISSUE TITLE
App crash if is clicked layout. 

### ISSUE THREAD

**Issue by brauliomendezj** [leomindez/EasyRecycler#1]
FATAL EXCEPTION: main
                                                                         Process: com.brauliomendez.jeweb, PID: 11949
                                                                         java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                             at java.util.ArrayList.get(ArrayList.java:310)
                                                                             at com.brauliomendez.jeweb.ui.fragment.SearchVacantsFragment$1.onItemClick(SearchVacantsFragment.java:71)
                                                                             at mx.leo.easyrecycler.util.RecyclerViewItemClickListener.onInterceptTouchEvent(RecyclerViewItemClickListener.kt:27)
                                                                             at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2539)
                                                                             at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2667)
                                                                             at android.view.View.dispatchTouchEvent(View.java:8160)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2428)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2151)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
                                                                             at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2311)
                                                                             at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1606)
                                                                             at android.app.Activity.dispatchTouchEvent(Activity.java:2617)
                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
                                                                             at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2259)
                                                                             at android.view.View.dispatchPointerEvent(View.java:8368)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4791)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4652)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4210)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4264)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4233)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4344)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4241)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4401)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4210)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4264)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4233)
                                                                         	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.j

**Comment by leomindez** [comment]
@BraulioMendez that issue was fixed. Please use 1.0.1 version
